# SPDX-FileCopyrightText: 2020 Ole Martin Bjorndalen <ombdalen@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

name: Test

on:
  push:
    branches: [
      main,
    ]
  pull_request:
    branches: [
      main,
    ]

jobs:
  style:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version-file: 'pyproject.toml'
      - name: Upgrade pip
        run: python3 -m pip install --upgrade pip
      - name: Install mido in dev mode
        run: python3 -m pip install --quiet .[dev]
      - name: Lint with flake
        run: flake8

  reuse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version-file: 'pyproject.toml'
      - name: Upgrade pip
        run: python3 -m pip install --upgrade pip
      - name: Install mido in dev mode
        run: python3 -m pip install --quiet .[dev]
      - name: Lint reuse
        run: reuse lint

  manifest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version-file: 'pyproject.toml'
      - name: Upgrade pip
        run: python3 -m pip install --upgrade pip
      - name: Install mido in dev mode
        run: python3 -m pip install --quiet .[dev]
      - name: Check manifest is complete
        run: check-manifest --verbose

  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version-file: 'pyproject.toml'
      - name: Upgrade pip
        run: python3 -m pip install --upgrade pip
      - name: Install mido in dev mode
        run: python3 -m pip install --quiet .[dev]
      - name: Check documentation
        run: sphinx-build -b linkcheck -j auto -q -W -E --keep-going docs docs/_build

  test:
    needs: [
      docs,
      manifest,
      reuse,
      style,
    ]
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [
          macOS-latest,
          ubuntu-latest,
          windows-latest,
        ]
        python-version: [
          '3.7',
          '3.8',
          '3.9',
          '3.10',
          '3.11',
        ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: python3 -m pip install --upgrade pip
      - name: Install mido in dev mode
        run: python3 -m pip install --quiet .[dev]
      - name: Test with pytest
        run: pytest
